// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
import * as db_city from "../db_city"
import { fetchJson } from "../client_utils";
// definition: API.System.City@CityList
export interface CityList {
  from: number;
  list: db_city.Full[];
}
export class __Main__ {
	private url: string;
	constructor(url: string) {
		this.url = url;
	}

	// action: API.System.City:AddCity
	async AddCity(city: db_city.Default): Promise<db_city.Default> {
		return fetchJson(this.url, "API.System.City:AddCity", "POST", { city })
	}

	// action: API.System.City:GetCityList
	async GetCityList(country: string): Promise<CityList> {
		return fetchJson(this.url, "API.System.City:GetCityList", "GET", { country })
	}
}

// tag-rt-api-builder-end