// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
import * as db_city from "../db_city"
import { fetchJson } from "../client_utils";
// definition: API.System.City@CityList
export interface CityList {
  from: number;
  list: db_city.Full[];
}
export class __Main__ {
	private url: string;
	constructor(url: string) {
		this.url = url;
	}

	// action: API.System.City:Query
	async Query(v: db_city.Query): Promise<CityList> {
		return fetchJson(this.url, "API.System.City:Query", "GET", { v })
	}

	// action: API.System.City:Create
	async Create(city: db_city.Create): Promise<db_city.Create> {
		return fetchJson(this.url, "API.System.City:Create", "POST", { city })
	}

	// action: API.System.City:Delete
	async Delete(v: db_city.Delete): Promise<db_city.Delete> {
		return fetchJson(this.url, "API.System.City:Delete", "POST", { v })
	}

	// action: API.System.City:Update
	async Update(v: db_city.Update): Promise<db_city.Update> {
		return fetchJson(this.url, "API.System.City:Update", "POST", { v })
	}
}

// tag-rt-api-builder-end