// tag-capi-builder-start: This file is generated by capi-builder, DO NOT EDIT.
import * as api_system_city from "../api_system_city";
export class __Main__ {
	public City: api_system_city.__Main__;
	constructor(url: string) {
		this.City = new api_system_city.__Main__(url);
	}

}

// tag-capi-builder-end