// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_geo
import (
	"github.com/ootiny/capi/server/runtime"
)

// definition: DB.Geo@Default
type Default struct {
	Id string `json:"id" required:"false"`
	Latitude float64 `json:"latitude" required:"false"`
	Longitude float64 `json:"longitude" required:"false"`
}

type DefaultBytes = []byte
func UnmarshalDefault(data []byte, v *Default) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func DefaultBytesToDefault(data []byte) (*Default, *runtime.Error) {
	var v Default
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

// definition: DB.Geo@Full
type Full struct {
	Id string `json:"id" required:"false"`
	Latitude float64 `json:"latitude" required:"false"`
	Longitude float64 `json:"longitude" required:"false"`
}

type FullBytes = []byte
func UnmarshalFull(data []byte, v *Full) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func FullBytesToFull(data []byte) (*Full, *runtime.Error) {
	var v Full
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}


// tag-rt-api-builder-end