// tag-capi-builder-start: This file is generated by capi-builder, DO NOT EDIT.
package db_geo
import (
	"github.com/ootiny/capi/server/runtime"
)

// definition: DB.Geo@Create
type Create struct {
	Id string `json:"id" required:"false"`
	Latitude float64 `json:"latitude" required:"false"`
	Longitude float64 `json:"longitude" required:"false"`
}

type CreateBytes = []byte
func UnmarshalCreate(data []byte, v *Create) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func CreateBytesToCreate(data []byte) (*Create, *runtime.Error) {
	var v Create
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

// definition: DB.Geo@Delete
type Delete struct {
	Id string `json:"id" required:"true"`
}

type DeleteBytes = []byte
func UnmarshalDelete(data []byte, v *Delete) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func DeleteBytesToDelete(data []byte) (*Delete, *runtime.Error) {
	var v Delete
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

// definition: DB.Geo@Full
type Full struct {
	Id string `json:"id" required:"false"`
	Latitude float64 `json:"latitude" required:"false"`
	Longitude float64 `json:"longitude" required:"false"`
}

type FullBytes = []byte
func UnmarshalFull(data []byte, v *Full) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func FullBytesToFull(data []byte) (*Full, *runtime.Error) {
	var v Full
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}


// tag-capi-builder-end