// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
// definition: DB.Geo@Default
export interface Default {
  id: string;
  latitude: number;
  longitude: number;
}

// definition: DB.Geo@Full
export interface Full {
  id: string;
  latitude: number;
  longitude: number;
}

// tag-rt-api-builder-end