// tag-capi-builder-start: This file is generated by capi-builder, DO NOT EDIT.
// definition: DB.Geo@Create
export interface Create {
  id: string;
  latitude: number;
  longitude: number;
}

// definition: DB.Geo@Delete
export interface Delete {
  id: string;
}

// definition: DB.Geo@Full
export interface Full {
  id: string;
  latitude: number;
  longitude: number;
}

// tag-capi-builder-end