// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package db_city
import (
	"github.com/ootiny/capi/server/runtime/db_geo"
	"github.com/ootiny/capi/server/runtime"
)

// definition: DB.City@Default
type Default struct {
	Age int64 `json:"age" required:"true"`
	Area float64 `json:"area" required:"true"`
	Str_list []string `json:"str_list" required:"true"`
	Name_16 string `json:"name_16" required:"true"`
	Str_map map[string]string `json:"str_map" required:"true"`
	Geo_list db_geo.Default `json:"geo_list" required:"true"`
	Geo_map db_geo.Default `json:"geo_map" required:"true"`
	Geo db_geo.Default `json:"geo" required:"false"`
	Active bool `json:"active" required:"false"`
	Id string `json:"id" required:"true"`
	Name_32 string `json:"name_32" required:"true"`
	Name_64 string `json:"name_64" required:"true"`
	Name_256 string `json:"name_256" required:"true"`
	Name string `json:"name" required:"true"`
}

type DefaultBytes = []byte
func UnmarshalDefault(data []byte, v *Default) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func DefaultBytesToDefault(data []byte) (*Default, *runtime.Error) {
	var v Default
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

// definition: DB.City@Full
type Full struct {
	Id string `json:"id" required:"true"`
	Name_16 string `json:"name_16" required:"true"`
	Name_32 string `json:"name_32" required:"true"`
	Name_64 string `json:"name_64" required:"true"`
	Name_256 string `json:"name_256" required:"true"`
	Name string `json:"name" required:"true"`
	Age int64 `json:"age" required:"true"`
	Area float64 `json:"area" required:"true"`
	Str_list []string `json:"str_list" required:"true"`
	Str_map map[string]string `json:"str_map" required:"true"`
	Geo_list db_geo.Full `json:"geo_list" required:"true"`
	Geo_map db_geo.Full `json:"geo_map" required:"true"`
	Geo db_geo.Full `json:"geo" required:"false"`
	Active bool `json:"active" required:"false"`
}

type FullBytes = []byte
func UnmarshalFull(data []byte, v *Full) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func FullBytesToFull(data []byte) (*Full, *runtime.Error) {
	var v Full
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}

// definition: DB.City@Simple
type Simple struct {
	Id string `json:"id" required:"true"`
	Name string `json:"name" required:"true"`
}

type SimpleBytes = []byte
func UnmarshalSimple(data []byte, v *Simple) *runtime.Error {
	 return runtime.JsonUnmarshal(data, v)
}
func SimpleBytesToSimple(data []byte) (*Simple, *runtime.Error) {
	var v Simple
	if err := runtime.JsonUnmarshal(data, &v); err != nil {
		return nil, err
	}
	return &v, nil
}


// tag-rt-api-builder-end