// tag-capi-builder-start: This file is generated by capi-builder, DO NOT EDIT.
import * as db_geo from "../db_geo"
// definition: DB.City@Full
export interface Full {
  id: string;
  name_16: string;
  name_32: string;
  name_64: string;
  name_256: string;
  name: string;
  age: number;
  area: number;
  str_list: string[];
  str_map: { [key: string]: string };
  geo_list: db_geo.Full;
  geo_map: db_geo.Full;
  geo: db_geo.Full;
  active: boolean;
}

// definition: DB.City@Simple
export interface Simple {
  id: string;
  name: string;
}

// definition: DB.City@Create
export interface Create {
  active: boolean;
  age: number;
  area: number;
  geo: db_geo.Create;
  geo_list: db_geo.Create;
  geo_map: db_geo.Create;
  id: string;
  name: string;
  name_16: string;
  name_256: string;
  name_32: string;
  name_64: string;
  str_list: string[];
  str_map: { [key: string]: string };
}

// definition: DB.City@Delete
export interface Delete {
  id: string;
}

// tag-capi-builder-end