// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
import * as db_geo from "../db_geo"
// definition: DB.City@Default
export interface Default {
  age: number;
  area: number;
  geo_list: db_geo.Default;
  geo: db_geo.Default;
  id: string;
  name_16: string;
  name_32: string;
  name_64: string;
  str_list: string[];
  str_map: { [key: string]: string };
  geo_map: db_geo.Default;
  active: boolean;
  name_256: string;
  name: string;
}

// definition: DB.City@Full
export interface Full {
  id: string;
  name_16: string;
  name_32: string;
  name_64: string;
  name_256: string;
  name: string;
  age: number;
  area: number;
  str_list: string[];
  str_map: { [key: string]: string };
  geo_list: db_geo.Full;
  geo_map: db_geo.Full;
  geo: db_geo.Full;
  active: boolean;
}

// definition: DB.City@Simple
export interface Simple {
  id: string;
  name: string;
}

// tag-rt-api-builder-end