// tag-capi-builder-start: This file is generated by capi-builder, DO NOT EDIT.
import * as api_system from "./api_system";
export class Client {
	public System: api_system.__Main__;
	constructor(url: string) {
		this.System = new api_system.__Main__(url);
	}

}

// tag-capi-builder-end