name: Lint

on:
  push:
    branches:
      - master
      - dev

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          args: --timeout 5m0s
