// tag-rt-api-builder-start: This file is generated by rt-builder, DO NOT EDIT.
package runtime

import "embed"

//go:embed all:db
var gDBAssets embed.FS
var gDBManager *SQLManager

func GetDBManager() *SQLManager {
	return gDBManager
}

func init() {
	if dbManager, err := NewSQLManager(&gDBAssets); err != nil {
		panic(DebugError(err))
	} else if err := dbManager.Open(); err != nil {
		panic(DebugError(err))
	} else {
		gDBManager = dbManager
	}
}

// tag-rt-api-builder-end